import com.example.rachunek.dto.Cart
import com.example.rachunek.model.ProductCategory
import com.example.rachunek.dto.CartProduct

import java.math.BigDecimal;

dialect "mvel"

rule "Przy zakupie minimum 5 sztuk pomidorów otrzymujemy 50% zniżki na całe zakupy dożytownio"
    when
        cart: Cart(countProductsByCategory(ProductCategory.Warzywa) > 3);
    then
        System.out.println(cart.findCheapestProductsByCategory(ProductCategory.Warzywa));
end;
//TODO lista promocji zamiast promocji prer produkt
